'use client';
import {useState,useRef,useEffect,useCallback,type ReactNode,type CSSProperties} from 'react';
import {Flower2,Music2,Maximize,Minimize,Volume2,VolumeX,Trophy,CircleHelp,Play,Pause,Lightbulb,RotateCcw,X,Check,Flag,Clock,Leaf,Sparkles,Heart} from 'lucide-react';
import {newGame,applyEvent,findPath,findPair,ended,MOTIFS,STAGE_SECONDS,STAGE_COUNT,LEGACY_STAGE_COUNT,type GameState,type GameEvent,type Point} from '../lib/game';
import {unlockAudio,sound,setBackgroundMusic,stopBackgroundMusic,audioStatus} from '../lib/sound';
import {tileArtStyle as artStyle} from '../lib/tile-art';
type Overlay='rules'|'scores'|'pause'|'restart'|'end'|'clear'|null;
type Score={id:string;name:string;score:number;stage:number;matched:number;elapsed:number;reason:string;created_at:number};
type Session={id:string;token:string;seed:number;stageCount?:number};
const fmt=(n:number)=>n.toLocaleString('ko-KR');
const formatTime=(ms:number)=>{const n=Math.max(0,Math.ceil(ms/1000));return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;};

function Modal({children,close,label}:{children:ReactNode;close?:()=>void;label:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return ()=>ref.current?.close();},[]);return <dialog ref={ref} className="modal" aria-label={label} onCancel={e=>{e.preventDefault();close?.();}}>{close&&<button className="close" onClick={close} aria-label="닫기"><X/></button>}{children}</dialog>;}
function ArcadeFeedback({good,combo}:{good:boolean;combo:number}){
 const word=combo>=6?'FANTASTIC!':combo>=3?'AMAZING!':combo>1?'GREAT!':'NICE!';
 return <div className={`feedback-layer ${good?'success-feedback':'error-feedback'} ${combo>=6?'super-combo':''}`} role="status" aria-live="polite">
  <div className="feedback-burst" aria-hidden="true">{Array.from({length:good?14:6},(_,i)=><i key={i} style={{'--angle':`${i*(360/(good?14:6))}deg`,'--delay':`${i%4*.025}s`,'--distance':`${110+(i%3)*30}px`,'--spark-color':['#fff19a','#ff97c1','#99ffe1','#ccadff'][i%4]} as CSSProperties}>{good?(i%3?'✦':'♥'):'✧'}</i>)}</div>
  <div className="feedback-copy">{good?<><span className="arcade-word" aria-hidden="true">{[...word].map((letter,i)=><span key={i} style={{'--letter':i} as CSSProperties}>{letter}</span>)}</span><span className="sr-only">{word}</span><span className="combo-word">{combo>1?`${combo} COMBO!`:'딱 맞았어요!'}</span><strong className="points-pop">+200<span>점</span></strong><span className="combo-meta">+2초</span></>:<><span className="error-symbol" aria-hidden="true">!</span><strong className="error-title">앗, 다시 한 번!</strong><span className="error-explain">이 카드는 연결할 수 없어요</span><span className="error-penalty">−10<span>초</span></span></>}</div>
 </div>;
}
export default function Home(){
 const [game,setGame]=useState<GameState>(()=>newGame(47921));const g=useRef(game);const [started,setStarted]=useState(false),[starting,setStarting]=useState(false),[overlay,setOverlay]=useState<Overlay>(null),[selected,setSelected]=useState<number|null>(null),[remaining,setRemaining]=useState(240000),[volume,setVolume]=useState(.8),[fullscreen,setFullscreen]=useState(false),[notice,setNotice]=useState(''),[effect,setEffect]=useState<{path:Point[];id:number}|null>(null),[feedback,setFeedback]=useState(''),[name,setName]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[saveError,setSaveError]=useState(''),[scores,setScores]=useState<Score[]>([]),[scoreError,setScoreError]=useState(''),[loadingScores,setLoadingScores]=useState(false);
 const [feedbackId,setFeedbackId]=useState(0),[wrongTiles,setWrongTiles]=useState<number[]>([]);const [combo,setCombo]=useState(0);const comboRef=useRef(0),warningRef=useRef(false),tickRef=useRef(-1);
 const [music,setMusic]=useState(true),[musicVolume,setMusicVolume]=useState(.52);
 const session=useRef<Session|null>(null),events=useRef<GameEvent[]>([]),clock=useRef({elapsed:0,at:0,running:false}),lock=useRef(0),volumeRef=useRef(volume),overlayRef=useRef<Overlay>(null),startedRef=useRef(false),effectTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const elapsed=useCallback(()=>clock.current.elapsed+(clock.current.running?performance.now()-clock.current.at:0),[]);
 const freeze=useCallback(()=>{clock.current={elapsed:elapsed(),at:performance.now(),running:false};},[elapsed]);
 const resume=useCallback(()=>{if(g.current.status==='playing')clock.current={elapsed:clock.current.elapsed,at:performance.now(),running:true};},[]);
 const show=useCallback((next:Overlay)=>{freeze();overlayRef.current=next;setOverlay(next);},[freeze]);
 const close=useCallback(()=>{overlayRef.current=null;setOverlay(null);if(startedRef.current)resume();},[resume]);
 const inform=useCallback((message:string)=>{setNotice(message);},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4200);return ()=>clearTimeout(t);},[notice]);
 useEffect(()=>{volumeRef.current=volume;},[volume]);
 useEffect(()=>{try{const v=localStorage.getItem('bloom-volume-v1');if(v!==null&&Number.isFinite(+v))setVolume(Math.min(1,Math.max(0,+v)));}catch{}},[]);
 useEffect(()=>{try{const enabled=localStorage.getItem('bloom-music-v1');if(enabled!==null)setMusic(enabled==='true');const v=localStorage.getItem('bloom-music-volume-v2');if(v!==null&&Number.isFinite(+v))setMusicVolume(Math.min(1,Math.max(0,+v)));}catch{}},[]);
 useEffect(()=>{const update=()=>setBackgroundMusic(music&&started&&!overlay&&!document.hidden,musicVolume);update();document.addEventListener('visibilitychange',update);return()=>{document.removeEventListener('visibilitychange',update);stopBackgroundMusic();};},[music,musicVolume,started,overlay]);
 const toggleMusic=async()=>{await unlockAudio();setMusic(v=>{try{localStorage.setItem('bloom-music-v1',String(!v));}catch{}return !v;});};
 const changeMusicVolume=(v:number)=>{setMusicVolume(v);try{localStorage.setItem('bloom-music-volume-v2',String(v));}catch{}};
 useEffect(()=>{if(!started||overlay||game.status!=='playing')return;if(remaining>30000){warningRef.current=false;tickRef.current=-1;return;}if(!warningRef.current){warningRef.current=true;sound('urgent',volumeRef.current);}const seconds=Math.ceil(remaining/1000);if(seconds<=10&&seconds>0&&tickRef.current!==seconds){tickRef.current=seconds;sound('tick',volumeRef.current,11-seconds);}},[remaining,started,overlay,game.status]);
 const changeVolume=(v:number)=>{setVolume(v);try{localStorage.setItem('bloom-volume-v1',String(v));}catch{}};
 const loadScores=useCallback(async()=>{setLoadingScores(true);setScoreError('');try{const r=await fetch('/api/scores',{cache:'no-store'});const d=await r.json() as {scores:Score[];error?:string};if(!r.ok)throw new Error(d.error);setScores(d.scores);}catch(e){setScoreError(e instanceof Error?e.message:'기록을 불러오지 못했습니다.');}finally{setLoadingScores(false);}},[]);
 const toggleFullscreen=useCallback(async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{inform('브라우저 메뉴의 전체화면 또는 F11 키를 사용해 주세요.');}},[inform]);
 useEffect(()=>{const listener=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',listener);return ()=>document.removeEventListener('fullscreenchange',listener);},[]);
 const start=useCallback(async(full=false)=>{if(starting)return;await unlockAudio();if(full&&!document.fullscreenElement)void document.documentElement.requestFullscreen().catch(()=>{});setStarting(true);setSaveError('');try{const r=await fetch('/api/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stageCount:STAGE_COUNT})});const d=await r.json() as Session&{error?:string};if(!r.ok)throw new Error(d.error);session.current=d;events.current=[];const state=newGame(d.seed,d.stageCount??LEGACY_STAGE_COUNT);g.current=state;setGame(state);setRemaining(state.remainingMs);setSelected(null);setFeedback('');setEffect(null);setWrongTiles([]);if(effectTimer.current)clearTimeout(effectTimer.current);comboRef.current=0;setCombo(0);setSaved(false);setStarted(true);startedRef.current=true;overlayRef.current=null;setOverlay(null);clock.current={elapsed:0,at:performance.now(),running:true};lock.current=0;sound('start',volumeRef.current);}catch(e){inform(e instanceof Error?e.message:'게임을 시작하지 못했습니다. 다시 시도해 주세요.');}finally{setStarting(false);}},[inform,starting]);
 const act=useCallback((kind:GameEvent['kind'],a?:number,b?:number)=>{
 const old=g.current;const ev:GameEvent={kind,elapsed:Math.round(elapsed()),...(a===undefined?{}:{a,b})};
 const pair=kind==='hint'?findPair(old.board):a!==undefined&&b!==undefined?[a,b]:null;const path=pair?findPath(old.board,pair[0],pair[1]):null;
 const state=applyEvent(old,ev);events.current.push(ev);g.current=state;setGame(state);setRemaining(state.remainingMs);setSelected(null);
 if(kind==='pair'||kind==='hint'){setFeedbackId(n=>n+1);setWrongTiles([]);if(path&&state.matched>old.matched){comboRef.current++;setCombo(comboRef.current);sound('match',volumeRef.current,comboRef.current);setEffect({path,id:Date.now()});setFeedback('+200  ·  +2초');}else{comboRef.current=0;setCombo(0);setEffect(null);setWrongTiles([a,b].filter((n):n is number=>n!==undefined));sound('error',volumeRef.current);setFeedback('연결할 수 없어요  −10초');}lock.current=performance.now()+200;if(effectTimer.current)clearTimeout(effectTimer.current);effectTimer.current=setTimeout(()=>{setEffect(null);setFeedback('');setWrongTiles([]);},path&&state.matched>old.matched?1350:1650);}
 if(state.status==='stageclear'){sound('win',volumeRef.current);show('clear');}else if(ended(state.status)){if(state.status==='won')sound('win',volumeRef.current);show('end');}else if(kind==='next'){comboRef.current=0;setCombo(0);close();}
 return state;
 },[elapsed,show,close]);
 const choose=useCallback((i:number)=>{if(!startedRef.current||overlayRef.current||g.current.status!=='playing'||performance.now()<lock.current||g.current.board[i]<0)return;void unlockAudio();if(selected===null){setSelected(i);sound('select',volumeRef.current);}else act('pair',selected,i);},[selected,act]);
 const hint=useCallback(()=>{if(!startedRef.current||overlayRef.current||g.current.status!=='playing'||performance.now()<lock.current)return;if(!g.current.hints){inform('세 번의 힌트를 모두 사용했습니다.');return;}void unlockAudio();act('hint');},[act,inform]);
 const openScores=useCallback(()=>{show('scores');void loadScores();},[show,loadScores]);
 useEffect(()=>{if(!started)return;const t=setInterval(()=>{if(!clock.current.running)return;const s=g.current;const left=Math.max(0,s.remainingMs-(elapsed()-s.elapsed));setRemaining(left);if(left<=0&&s.status==='playing')act('timeout');},100);return ()=>clearInterval(t);},[started,elapsed,act]);
 useEffect(()=>{const visibility=()=>{if(document.hidden&&startedRef.current&&clock.current.running&&g.current.status==='playing')show('pause');};document.addEventListener('visibilitychange',visibility);return ()=>document.removeEventListener('visibilitychange',visibility);},[show]);
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;const key=e.key.toLowerCase();if(key==='f'){e.preventDefault();void toggleFullscreen();}if(key==='m')changeVolume(volumeRef.current>0?0:.8);if(key==='h')hint();if((key==='p'||e.code==='Space')&&startedRef.current&&g.current.status==='playing'){e.preventDefault();if(overlayRef.current==='pause')close();else if(!overlayRef.current)show('pause');}};window.addEventListener('keydown',listener);return ()=>window.removeEventListener('keydown',listener);},[close,show,hint,toggleFullscreen]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(started&&(!ended(g.current.status)||(!saved&&g.current.score>0))){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return ()=>window.removeEventListener('beforeunload',before);},[started,saved]);
 useEffect(()=>()=>{if(effectTimer.current)clearTimeout(effectTimer.current);},[]);
 const save=async()=>{if(saving||saved)return;setSaveError('');setSaving(true);try{const r=await fetch('/api/scores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:session.current?.id,token:session.current?.token,name,events:events.current})});const data=await r.json() as {record:Score;error?:string};if(!r.ok)throw new Error(data.error);if(data.record.score!==g.current.score)throw new Error('점수 확인에 실패했습니다. 다시 시도해 주세요.');setSaved(true);void loadScores();}catch(e){setSaveError(e instanceof Error?e.message:'점수 저장에 실패했습니다. 다시 시도해 주세요.');}finally{setSaving(false);}};
 // WebMCP exposes the same game actions, with no test-only state changes.
 const apiRef=useRef({start,act,show,close,elapsed});apiRef.current={start,act,show,close,elapsed};
 useEffect(()=>{type Context={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const register=(tool:unknown)=>{try{void Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
 register({name:'get_game_state',description:'현재 화면의 타일, 점수, 시간, 단계, 대화상자를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...g.current,remainingMs:Math.max(0,g.current.remainingMs-(apiRef.current.elapsed()-g.current.elapsed)),overlay:overlayRef.current,started:startedRef.current,audio:audioStatus()})});
 register({name:'start_game',description:'새 게임을 시작합니다. 진행 중인 게임은 덮어쓰지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async()=>{if(startedRef.current)throw new Error('이미 게임을 시작했습니다.');await apiRef.current.start(false);if(!startedRef.current)throw new Error('게임 시작 실패');return {started:true,stage:g.current.stage};}});
 register({name:'play_pairs',description:'화면의 타일 인덱스(0~119)를 이용해 순서대로 짝을 선택합니다. 잘못된 짝은 실제 게임과 같이 10초 차감합니다. 종료나 단계 완료 시 중단합니다.',inputSchema:{type:'object',properties:{pairs:{type:'array',maxItems:60,items:{type:'array',items:{type:'integer',minimum:0,maximum:119},minItems:2,maxItems:2}}},required:['pairs'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const pairs=(input as {pairs?:unknown})?.pairs;if(!Array.isArray(pairs)||pairs.length>60||pairs.some(p=>!Array.isArray(p)||p.length!==2||p.some(n=>!Number.isInteger(n)||n<0||n>=120)))throw new Error('올바른 타일 두 개를 지정해 주세요.');if(!startedRef.current||overlayRef.current||g.current.status!=='playing')throw new Error('게임을 진행 중일 때만 선택할 수 있습니다.');let played=0;for(const [a,b]of pairs){if(g.current.status!=='playing')break;apiRef.current.act('pair',a,b);played++;}return {played,status:g.current.status,score:g.current.score};}});
 return ()=>life.abort();},[]);
 const count=game.board.filter(n=>n>=0).length;const paused=started&&!!overlay&&game.status==='playing';
 return <main className={`game-app ${started&&remaining<=30000&&game.status==='playing'?'time-pressure':''} ${combo>=6?'bloom-streak':''}`}><div className="garden-lights" aria-hidden="true"><i/><i/><i/><i/><i/></div><header><div className="brand"><span className="brand-flower"><Flower2/></span><b>BLOOM<span className="brand-sub">꽃과 과일 마작</span></b></div><nav aria-label="게임 메뉴"><button onClick={openScores}><Trophy/> 기록실</button><button onClick={()=>show('rules')}><CircleHelp/> 게임 방법</button><button onClick={()=>{void unlockAudio();changeVolume(volume?0:.8);}} aria-label={volume?'효과음 끄기':'효과음 켜기'} title="효과음 · M">{volume?<Volume2/>:<VolumeX/>}</button><button onClick={()=>void toggleMusic()} aria-label={music?'배경음악 끄기':'배경음악 켜기'} aria-pressed={music} title="오케스트라 배경음악"><Music2/><span className="music-label">배경음악</span></button><button onClick={toggleFullscreen}>{fullscreen?<Minimize/>:<Maximize/>} {fullscreen?'화면 복귀':'전체화면'}</button></nav></header>
 <section className="game-top"><div className="garden-title"><span className="eyebrow"><Sparkles/> FLOWER POP GARDEN</span><h1>{game.stage===1?'꽃피는 콤보 타임!':`정원 ${game.stage}, 계속 피워봐요!`}</h1></div><div className="stats"><div className="score-stat"><Trophy aria-hidden="true"/><span>현재 점수</span><strong data-testid="score" key={game.score}>{fmt(game.score)}</strong></div><div className={`timer-stat ${remaining<30000&&started?'urgent':''}`}><Clock aria-hidden="true"/><span>{paused?'일시정지':'남은 시간'}</span><strong data-testid="timer">{formatTime(remaining)}</strong></div><div className="tiles-stat"><Flower2 aria-hidden="true"/><span>남은 타일</span><strong data-testid="tile-count">{count} <small>/ 120</small></strong></div></div></section>
 <section className="board-shell" aria-label="마작 게임판"><div className="board-caption"><span>{game.stage===game.stageCount?'마지막':`${game.stage}번째`} 정원 <em>{String(game.stage).padStart(2,'0')} / {game.stageCount}</em></span><div className={`streak-meter ${combo>0?'active':''}`} aria-label={`연속 성공 ${combo}회`}><Sparkles/><b>{combo>0?`${combo} COMBO`:'READY TO BLOOM'}</b><span className="streak-pips" aria-hidden="true">{Array.from({length:6},(_,i)=><i key={i} className={i<Math.min(combo,6)?'lit':''}/>)}</span></div></div><div className={`board ${paused?'obscured':''}`}><div className="tile-grid" role="group" aria-label="15열 8행 타일"><div className="board-watermark" aria-hidden="true"><Flower2/><span>BLOOM</span></div>{game.board.map((type,i)=><button data-testid={`tile-${i}`} data-motif={type} className={`tile ${selected===i?'selected':''} ${wrongTiles.includes(i)?'tile-wrong':''} ${type<0?'removed':''}`} key={i} aria-label={type<0?`빈 칸 ${i+1}`:`${Math.floor(i/15)+1}행 ${i%15+1}열 ${MOTIFS[type]}`} aria-pressed={selected===i} disabled={type<0||!started||!!overlay||game.status!=='playing'} onClick={()=>choose(i)}><span className="tile-art" style={type<0?undefined:artStyle(type)}/></button>)}{effect&&<svg className="connection" viewBox="0 0 1500 800" preserveAspectRatio="none" aria-hidden="true" key={effect.id}><polyline points={effect.path.map(p=>`${p.x*100+50},${p.y*100+50}`).join(' ')} fill="none" stroke="#e1ffa4" strokeWidth="8" strokeLinecap="round" strokeLinejoin="round"/>{[effect.path[0],effect.path.at(-1)!].map((p,i)=><circle key={i} cx={p.x*100+50} cy={p.y*100+50} r="38" fill="#f0ffcb" className="burst"/>)}</svg>}</div></div>
 {!started&&<div className="start-veil"><div className="start-card"><div className="start-bouquet" aria-hidden="true">{[0,17,3].map((type,i)=><div className={`bouquet-tile bouquet-${i}`} key={type}><span className="tile-art" style={artStyle(type)}/></div>)}<Sparkles/></div><span className="eyebrow">BLOOM MAHJONG</span><h2>톡! 톡! 연결하면<br/><em>행복이 팡!</em></h2><p>꽃과 과일을 맞추고, 콤보를 피워봐요.<br/>반짝이는 {STAGE_COUNT}개의 정원이 기다려요!</p><button className="primary" onClick={()=>start(true)} disabled={starting}><Play/>{starting?'정원을 준비하는 중…':'전체화면으로 시작'}</button><button className="text-button" onClick={()=>start(false)} disabled={starting}>현재 화면으로 시작</button><span className="start-note">120개의 타일 · {STAGE_COUNT}개의 스테이지</span></div></div>}
<div className="time-track"><span style={{width:`${Math.min(100,remaining/(STAGE_SECONDS[game.stage-1]*1000)*100)}%`}}/></div></section>
 {!!feedback&&!overlay&&<ArcadeFeedback key={feedbackId} good={feedback.startsWith('+')} combo={combo}/>}
 <footer><div className="stage-track" aria-label={`${game.stageCount}단계 중 ${game.stage}단계`}><span className="current" data-total={game.stageCount}>{String(game.stage).padStart(2,'0')}</span><div className="stage-progress" aria-hidden="true">{Array.from({length:game.stageCount},(_,i)=><i key={i} className={i===game.stage-1?'active':i<game.stage-1?'done':''}/>)}</div></div><div className="tools"><button onClick={hint} disabled={!started||!!overlay||game.status!=='playing'||!game.hints}><Lightbulb/> 힌트 <b>{game.hints}</b><kbd>H</kbd></button><button onClick={()=>show('pause')} disabled={!started||!!overlay||game.status!=='playing'}><Pause/> 일시정지 <kbd>P</kbd></button><button onClick={()=>{if(!started)void start(false);else if(ended(game.status))show('end');else show('restart');}}><RotateCcw/> 새 게임</button></div><span className="footer-note"><Heart/> 한 쌍 +200점 · +2초</span></footer>
 {notice&&<div className="toast" role="status">{notice}</div>}
 {overlay==='rules'&&<Modal label="게임 방법" close={close}><span className="eyebrow">HOW TO PLAY</span><h2>같은 그림, 이어지는 정원</h2><p className="modal-intro">같은 꽃이나 과일 두 개를 클릭해 모두 없애세요.</p><div className="rule-demo"><div className="mini-tile"><span className="tile-art" style={artStyle(0)}/></div><div className="rule-line"/><div className="mini-tile"><span className="tile-art" style={artStyle(0)}/></div><Check/></div><ul className="rules"><li><b>연결은 세 개의 직선 이내</b><span>다른 타일을 통과하지 않고, 최대 두 번 꺾어 연결합니다. 게임판 바깥의 빈 공간도 이용할 수 있어요.</span></li><li><b>정확하게 맞출수록 여유롭게</b><span>한 쌍을 맞추면 200점과 2초를 얻고, 잘못된 짝을 고르면 10초가 줄어듭니다. 같은 타일을 두 번 눌러도 오답입니다. 콤보는 연속 성공 연출이며 점수 배수는 없습니다.</span></li><li><b>힌트는 게임 전체에서 세 번</b><span>힌트는 연결 가능한 한 쌍을 자동으로 없애며 점수와 시간을 똑같이 받습니다.</span></li><li><b>{game.stageCount}개의 정원</b><span>각 단계는 120장입니다. 제한 시간은 4분·3분이 번갈아 적용됩니다. 완료 시 단계 × 100점과 남은 초 × 10점이 추가됩니다.</span></li><li><b>시간이 없거나 짝이 막히면 종료</b><span>타일은 이동하지 않으며 자동으로 섞이지 않습니다. 종료 후 이름을 입력해 점수를 저장할 수 있어요.</span></li></ul><div className="rule-source">규칙 참고: <a href="http://www.game24.co.kr/game.php?gamecode=mahjong" target="_blank" rel="noreferrer">게임24 퍼즐마작2</a><br/>원본 안내의 ‘3번’은 실제 판정 기준인 직선 3개로 적용했습니다.</div><div className="volume-control"><Volume2 size={18}/><label htmlFor="volume">효과음 크기</label><input id="volume" type="range" min="0" max="1" step=".05" value={volume} onChange={e=>{void unlockAudio();changeVolume(+e.target.value);}} onPointerUp={()=>sound('match',volume)}/></div><div className="volume-control"><Music2 size={18}/><label htmlFor="music-volume">배경음악 크기</label><input id="music-volume" type="range" min="0" max="1" step=".05" value={musicVolume} onChange={e=>changeMusicVolume(+e.target.value)}/></div><p className="music-credit">BGM: <a href="https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1400024" target="_blank" rel="noreferrer">Run Amok — Kevin MacLeod</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a></p><button className="primary wide" onClick={close}>알겠어요</button></Modal>}
 {overlay==='pause'&&<Modal label="일시정지" close={close}><div className="center-modal"><Pause className="modal-symbol"/><span className="eyebrow">TAKE A BREATH</span><h2>잠시 쉬어 가세요.</h2><p>시간도 함께 멈춰 있어요.</p><button className="primary wide" onClick={close}><Play/> 계속하기</button><button className="text-button" onClick={()=>show('restart')}>이번 게임 마치기</button></div></Modal>}
 {overlay==='restart'&&<Modal label="게임 마치기" close={close}><h2>이번 게임을 마칠까요?</h2><p className="modal-intro">지금까지 얻은 {fmt(game.score)}점을 저장한 뒤<br/>새로운 게임을 시작할 수 있어요.</p><button className="primary wide" onClick={()=>act('quit')}><Flag/> 게임 마치고 점수 확인</button><button className="text-button wide" onClick={close}>계속 플레이</button></Modal>}
 {overlay==='clear'&&<Modal label="스테이지 완료"><div className="center-modal"><Flower2 className="modal-symbol"/><span className="eyebrow">GARDEN COMPLETE</span><h2>{game.stage}번째 정원을 완성했어요.</h2><div className="result-score">{fmt(game.score)}<span>점</span></div><p>완료 보너스 <b>+{fmt(game.bonus)}점</b></p><button className="primary wide" onClick={()=>act('next')}><Play/> 다음 정원으로</button></div></Modal>}
 {overlay==='end'&&<Modal label="점수 저장"><div className="center-modal"><Trophy className="modal-symbol"/><span className="eyebrow">{game.status==='won'?'ALL GARDENS COMPLETE':'YOUR GARDEN RECORD'}</span><h2>{game.status==='won'?`${game.stageCount}개 정원을 모두 완성했어요!`:game.status==='timeout'?'시간이 다 되었어요.':game.status==='stuck'?'연결할 수 있는 짝이 없어요.':'이번 정원의 기록'}</h2><div className="result-score">{fmt(game.score)}<span>점</span></div><div className="result-detail"><span>도달 단계 <b>{game.stage} / {game.stageCount}</b></span><span>맞춘 타일 <b>{game.matched*2}장</b></span></div>{!saved?<form onSubmit={e=>{e.preventDefault();void save();}}><h3>점수를 저장할까요?</h3><label className="name-label" htmlFor="player-name">기록에 남길 이름</label><input id="player-name" value={name} onChange={e=>setName(e.target.value)} placeholder="이름을 입력하세요" maxLength={16} required autoComplete="nickname" disabled={saving}/><p className="save-note">점수는 플레이 결과로 자동 입력됩니다.</p>{saveError&&<p className="error" role="alert">{saveError}</p>}<button className="primary wide" type="submit" disabled={saving}>{saving?'점수를 저장하는 중…':'점수 저장하기'}</button><button className="text-button wide" type="button" disabled={saving||starting} onClick={()=>start(false)}>저장하지 않고 새 게임</button></form>:<><div className="saved-message" role="status"><Check/> {name}님의 점수를 저장했어요.</div><button className="primary wide" onClick={openScores}><Trophy/> 기록실에서 보기</button><button className="text-button wide" onClick={()=>start(false)} disabled={starting}>새 게임 시작</button></>}</div></Modal>}
 {overlay==='scores'&&<Modal label="기록실" close={()=>{if(ended(game.status)&&started)show('end');else close();}}><span className="eyebrow">THE HALL OF BLOOM</span><h2>차곡차곡, 나의 기록</h2><p className="modal-intro">저장한 점수를 높은 순서대로 볼 수 있어요.</p>{loadingScores?<p className="empty">기록을 불러오는 중…</p>:scoreError?<div className="empty error" role="alert">{scoreError}<button className="text-button" onClick={loadScores}>다시 불러오기</button></div>:scores.length===0?<div className="empty"><Leaf/><h3>아직 피어난 기록이 없어요.</h3><p>게임을 마치고 첫 번째 점수를 남겨 보세요.</p></div>:<div className="score-list"><table><thead><tr><th>순위</th><th>이름</th><th>점수</th><th>단계</th></tr></thead><tbody>{scores.map((s,i)=><tr key={s.id} className={s.id===session.current?.id?'own-score':''}><td>{i<3?<Trophy size={17}/>:i+1}</td><td><b>{s.name}</b><small>{new Date(s.created_at).toLocaleDateString('ko-KR')}</small></td><td>{fmt(s.score)}</td><td>{s.stage}단계</td></tr>)}</tbody></table></div>}<button className="primary wide" onClick={()=>{if(ended(game.status)&&started)show('end');else close();}}>{started&&!ended(game.status)?'게임으로 돌아가기':'확인'}</button></Modal>}
 </main>;
}
